### ISSUE TITLE
名刺の略歴内の文の助詞の間違いについて

### ISSUE THREAD

**Issue by linuxmetel** [senooken/BusinessCard#1]
名刺の略歴内の文に「Tueに建設コンサルタントに入社。」とありますが、正しくは「Tueに建設コンサルタントとして入社。」ではないでしょうか？

**Comment by senooken** [comment]
わざわざ閲覧いただいてコメントありがとうございます。

しかし，この表記でも問題ありません。「建設コンサルタント」が個人だけでなく特定業種の企業も意味するのです。

参考: [建設コンサルタント - Wikipedia](https://ja.wikipedia.org/wiki/%E5%BB%BA%E8%A8%AD%E3%82%B3%E3%83%B3%E3%82%B5%E3%83%AB%E3%82%BF%E3%83%B3%E3%83%88)

「コンサルタント」という用語が，個人だけでなく法人も指すのです。
